//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetChatem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Actualite
    {
        [DisplayName("Numéro de l'actualité")]
        [Required(ErrorMessage = "Obligatoire.")]
        public string numActualite { get; set; }

        [DisplayName("Titre de l'actualité")]
        [Required(ErrorMessage = "Obligatoire.")]
        public string titreActualite { get; set; }

        [DisplayName("Desription de l'actualité")]
        public string descriptionActualite { get; set; }
    }
}
