//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetChatem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Evenement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evenement()
        {
            this.UtilisateurEvenements = new HashSet<UtilisateurEvenement>();
        }

        [DisplayName("Numéro de l'événement")]
        [Required(ErrorMessage = "Obligatoire.")]
        public string numEvenement { get; set; }

        [DisplayName("Titre ou nom de l'événement")]
        [Required(ErrorMessage = "Obligatoire.")]
        public string nomEvenement { get; set; }

        [DisplayName("Description de l'événement")]
        [Required(ErrorMessage = "Obligatoire.")]
        public string descriptionEvenement { get; set; }

        [DisplayName("Date de l'événement")]
        [Required(ErrorMessage = "Obligatoire.")]
        public System.DateTime dateEvenement { get; set; }

        [DisplayName("Heure de l'événement")]
        [Required(ErrorMessage = "Obligatoire.")]
        public System.TimeSpan heureEvenement { get; set; }

        [DisplayName("Lieu de l'événement")]
        [Required(ErrorMessage = "Obligatoire.")]
        public string lieuEvenement { get; set; }

        [DisplayName("Prix d'entrée à l'événement")]
        [Required(ErrorMessage = "Obligatoire.")]
        public decimal prixEntree { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UtilisateurEvenement> UtilisateurEvenements { get; set; }
    }
}
