//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetChatem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class FoireAuxQuestion
    {
        [DisplayName("Identifiant")]
        [Required(ErrorMessage = "Obligatoire.")]
        public string identifiantFAQ { get; set; }

        [DisplayName("Objet")]
        [Required(ErrorMessage = "Obligatoire.")]
        public string objet { get; set; }

        [DisplayName("Votre commentaire ou question")]
        [Required(ErrorMessage = "Obligatoire.")]
        public string question { get; set; }

        [DisplayName("Votre nom")]
        [Required(ErrorMessage = "Obligatoire.")]
        public string proprietaireQuestion { get; set; }

        [DisplayName("Date")]
        [Required(ErrorMessage = "Obligatoire.")]
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
