//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetChatem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Partenaire
    {
        [DisplayName("Identifiant du partenaire")]
        [Required(ErrorMessage = "Obligatoire.")]
        public string numPartenaire { get; set; }

        [DisplayName("Numéro d'utilisateur du partenaire")]
        [Required(ErrorMessage = "Obligatoire.")]
        public string numUtilisateurPartenaire { get; set; }

        [DisplayName("Nom du partenaire")]
        public string nomPartenaire { get; set; }

        [DisplayName("Domaine d'activité")]
        [Required(ErrorMessage = "Obligatoire.")]
        public string domaineActivite { get; set; }

        [DisplayName("Téléphone")]
        [Required(ErrorMessage = "Obligatoire.")]
        public Nullable<decimal> telephone { get; set; }

        [DisplayName("Courriel")]
        [Required(ErrorMessage = "Obligatoire.")]
        public string courriel { get; set; }

        [DisplayName("Adresse")]
        public string adresse { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
