//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetChatem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Projet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Projet()
        {
            this.Utilisateurs = new HashSet<Utilisateur>();
        }

        [DisplayName("Numéro du projet")]
        [Required(ErrorMessage = "Obligatoire.")]
        public string numProjet { get; set; }

        [DisplayName("Titre du projet")]
        [Required(ErrorMessage = "Obligatoire.")]
        public string titreProjet { get; set; }

        [DisplayName("Description du projet")]
        [Required(ErrorMessage = "Obligatoire.")]
        public string descriptionProjet { get; set; }

        [DisplayName("Montant total de réalisation du projet")]
        [Required(ErrorMessage = "Obligatoire.")]
        public decimal montantRealisation { get; set; }

        [DisplayName("Taux de participation par membre")]
        [Required(ErrorMessage = "Obligatoire.")]
        public decimal tauxParticipation { get; set; }

        [DisplayName("État du projet")]
        [Required(ErrorMessage = "Obligatoire.")]
        public string nomEtatProjet { get; set; }
    
        public virtual EtatProjet EtatProjet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utilisateur> Utilisateurs { get; set; }
    }
}
