//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetChatem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Repertoire
    {
        [DisplayName("Identifiant")]
        [Required(ErrorMessage = "Obligatoire.")]
        public string identifiant { get; set; }

        [DisplayName("Nom")]
        [Required(ErrorMessage = "Obligatoire.")]
        public string proprietaire { get; set; }

        [DisplayName("activité exercée")]
        [Required(ErrorMessage = "Obligatoire.")]
        public string activiteExercee { get; set; }

        [DisplayName("Description de l'activité")]
        public string descriptionActivite { get; set; }

        [DisplayName("Contact")]
        [Required(ErrorMessage = "Obligatoire.")]
        public string contact { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
