//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetChatem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Transaction
    {
        [DisplayName("Numéro de transaction")]
        [Required(ErrorMessage = "Obligatoire.")]
        public string numTransaction { get; set; }

        [DisplayName("Numéro d'utilisateur")]
        [Required(ErrorMessage = "Obligatoire.")]
        public string numUtilisateurTransaction { get; set; }

        [DisplayName("Montant de la transaction")]
        [Required(ErrorMessage = "Obligatoire.")]
        public decimal montantTransaction { get; set; }

        [DisplayName("Date de la transaction")]
        [Required(ErrorMessage = "Obligatoire.")]
        public System.DateTime dateTransaction { get; set; }

        [DisplayName("Motif de la transaction")]
        [Required(ErrorMessage = "Obligatoire.")]
        public string motifTransaction { get; set; }
    
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
