//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetChatem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class UtilisateurEvenement
    {
        [DisplayName("Numéro de l'événement")]
        [Required(ErrorMessage = "Obligatoire.")]
        public string numEvenement { get; set; }

        [DisplayName("Numéro d'utilisateur du promoteur")]
        [Required(ErrorMessage = "Obligatoire.")]
        public string numUtilisateur { get; set; }

        [DisplayName("Nom de l'événement")]
        public string nomEvenement { get; set; }

        [DisplayName("Nom du promoteur")]
        public string nomUtilisateur { get; set; }

        [DisplayName("Téléphone")]
        public Nullable<decimal> telephone { get; set; }

        [DisplayName("Courriel")]
        [Required(ErrorMessage = "Obligatoire.")]
        public string courriel { get; set; }
    
        public virtual Evenement Evenement { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
    }
}
