//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetChatem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Utilisateur
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Utilisateur()
        {
            this.FoireAuxQuestions = new HashSet<FoireAuxQuestion>();
            this.Partenaires = new HashSet<Partenaire>();
            this.Repertoires = new HashSet<Repertoire>();
            this.Transactions = new HashSet<Transaction>();
            this.UtilisateurEvenements = new HashSet<UtilisateurEvenement>();
            this.Projets = new HashSet<Projet>();
        }

        [DisplayName("Numéro d'utilisateur")]
        public string numUtilisateur { get; set; }

        [DisplayName("Nom complet")]
        [Required(ErrorMessage = "Vous devez obligatoirement entrer votre nom.")]
        public string nomUtilisateur { get; set; }

        [DisplayName("Téléphone")]
        public Nullable<decimal> numTelephone { get; set; }

        [DisplayName("Courriel")]
        [Required(ErrorMessage = "Vous devez obligatoirement entrer votre adresse courriel.")]
        public string courriel { get; set; }

        [DisplayName("Profession ou secteur d'activité")]
        public string profession { get; set; }

        [DisplayName("Ville de résidence")]
        public string villeResidence { get; set; }

        [DisplayName("Pays d'origine")]
        public string paysOrigine { get; set; }

        [DisplayName("Cochez pour rendre vos informations personnelles visibles")]
        public bool visibiliteInfos { get; set; }

        [DisplayName("Type d'utilisateur")]
        public string nomtypeUtilisateur { get; set; }

        [DisplayName("Mot de passe")]
        [Required(ErrorMessage = "Le mot de passe est obligatoire.")]
        public string motDePasse { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoireAuxQuestion> FoireAuxQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partenaire> Partenaires { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Repertoire> Repertoires { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual TypeUtilisateur TypeUtilisateur { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UtilisateurEvenement> UtilisateurEvenements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Projet> Projets { get; set; }
    }
}
